// Code generated by protoc-gen-go.
// source: MessageRouting.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	MessageRouting.proto

It has these top-level messages:
	HeartbeatInit
	HeartbeatInitResponse
	Heartbeat
	HeartbeatResponse
	UserLogin
	UserLoginResponse
	UserLogout
	UserLogoutResponse
	Message
	MessageResponse
	ReceiveMessageAck
	NormalMessage
	NormalMessageAck
*/
package common

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MessageCommand int32

const (
	MessageCommand_HEARTBEAT_INIT          MessageCommand = 0
	MessageCommand_HEARTBEAT               MessageCommand = 1
	MessageCommand_USER_LOGIN              MessageCommand = 2
	MessageCommand_USER_LOGOUT             MessageCommand = 3
	MessageCommand_MESSAGE                 MessageCommand = 4
	MessageCommand_RECEIVE_MESSAGE_ACK     MessageCommand = 5
	MessageCommand_NORMARL_MESSAGE_ACK     MessageCommand = 6
	MessageCommand_HEARTBEAT_INIT_RESPONSE MessageCommand = 100
	MessageCommand_HEARTBEAT_RESPONSE      MessageCommand = 101
	MessageCommand_USER_LOGIN_RESPONSE     MessageCommand = 102
	MessageCommand_USER_LOGOUT_RESPONSE    MessageCommand = 103
	MessageCommand_MESSAGE_RESPONSE        MessageCommand = 104
	MessageCommand_RECEIVE_MESSAGE         MessageCommand = 200
	MessageCommand_NORMARL_MESSAGE         MessageCommand = 201
)

var MessageCommand_name = map[int32]string{
	0:   "HEARTBEAT_INIT",
	1:   "HEARTBEAT",
	2:   "USER_LOGIN",
	3:   "USER_LOGOUT",
	4:   "MESSAGE",
	5:   "RECEIVE_MESSAGE_ACK",
	6:   "NORMARL_MESSAGE_ACK",
	100: "HEARTBEAT_INIT_RESPONSE",
	101: "HEARTBEAT_RESPONSE",
	102: "USER_LOGIN_RESPONSE",
	103: "USER_LOGOUT_RESPONSE",
	104: "MESSAGE_RESPONSE",
	200: "RECEIVE_MESSAGE",
	201: "NORMARL_MESSAGE",
}
var MessageCommand_value = map[string]int32{
	"HEARTBEAT_INIT":          0,
	"HEARTBEAT":               1,
	"USER_LOGIN":              2,
	"USER_LOGOUT":             3,
	"MESSAGE":                 4,
	"RECEIVE_MESSAGE_ACK":     5,
	"NORMARL_MESSAGE_ACK":     6,
	"HEARTBEAT_INIT_RESPONSE": 100,
	"HEARTBEAT_RESPONSE":      101,
	"USER_LOGIN_RESPONSE":     102,
	"USER_LOGOUT_RESPONSE":    103,
	"MESSAGE_RESPONSE":        104,
	"RECEIVE_MESSAGE":         200,
	"NORMARL_MESSAGE":         201,
}

func (x MessageCommand) Enum() *MessageCommand {
	p := new(MessageCommand)
	*p = x
	return p
}
func (x MessageCommand) String() string {
	return proto.EnumName(MessageCommand_name, int32(x))
}
func (x *MessageCommand) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageCommand_value, data, "MessageCommand")
	if err != nil {
		return err
	}
	*x = MessageCommand(value)
	return nil
}

type HeartbeatInit struct {
	LastTimeout      *int32  `protobuf:"varint,1,req,name=last_timeout" json:"last_timeout,omitempty"`
	Extra            *string `protobuf:"bytes,2,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeartbeatInit) Reset()         { *m = HeartbeatInit{} }
func (m *HeartbeatInit) String() string { return proto.CompactTextString(m) }
func (*HeartbeatInit) ProtoMessage()    {}

func (m *HeartbeatInit) GetLastTimeout() int32 {
	if m != nil && m.LastTimeout != nil {
		return *m.LastTimeout
	}
	return 0
}

func (m *HeartbeatInit) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type HeartbeatInitResponse struct {
	NextHeartbeat    *int32  `protobuf:"varint,1,opt,name=next_heartbeat" json:"next_heartbeat,omitempty"`
	Extra            *string `protobuf:"bytes,2,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeartbeatInitResponse) Reset()         { *m = HeartbeatInitResponse{} }
func (m *HeartbeatInitResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatInitResponse) ProtoMessage()    {}

func (m *HeartbeatInitResponse) GetNextHeartbeat() int32 {
	if m != nil && m.NextHeartbeat != nil {
		return *m.NextHeartbeat
	}
	return 0
}

func (m *HeartbeatInitResponse) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type Heartbeat struct {
	LastDelay        *int32  `protobuf:"varint,1,opt,name=last_delay" json:"last_delay,omitempty"`
	Extra            *string `protobuf:"bytes,2,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}

func (m *Heartbeat) GetLastDelay() int32 {
	if m != nil && m.LastDelay != nil {
		return *m.LastDelay
	}
	return 0
}

func (m *Heartbeat) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type HeartbeatResponse struct {
	NextHeartbeat    *int32  `protobuf:"varint,1,opt,name=next_heartbeat" json:"next_heartbeat,omitempty"`
	Extra            *string `protobuf:"bytes,2,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}

func (m *HeartbeatResponse) GetNextHeartbeat() int32 {
	if m != nil && m.NextHeartbeat != nil {
		return *m.NextHeartbeat
	}
	return 0
}

func (m *HeartbeatResponse) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type UserLogin struct {
	UserId           *string `protobuf:"bytes,1,req,name=user_id" json:"user_id,omitempty"`
	Channel          *string `protobuf:"bytes,2,opt,name=channel" json:"channel,omitempty"`
	Version          *string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Token            *string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	Extra            *string `protobuf:"bytes,5,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserLogin) Reset()         { *m = UserLogin{} }
func (m *UserLogin) String() string { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()    {}

func (m *UserLogin) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *UserLogin) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func (m *UserLogin) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *UserLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *UserLogin) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type UserLoginResponse struct {
	Status           *bool   `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	Extra            *string `protobuf:"bytes,2,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserLoginResponse) Reset()         { *m = UserLoginResponse{} }
func (m *UserLoginResponse) String() string { return proto.CompactTextString(m) }
func (*UserLoginResponse) ProtoMessage()    {}

func (m *UserLoginResponse) GetStatus() bool {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return false
}

func (m *UserLoginResponse) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type UserLogout struct {
	UserId           *string `protobuf:"bytes,1,req,name=user_id" json:"user_id,omitempty"`
	Extra            *string `protobuf:"bytes,2,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserLogout) Reset()         { *m = UserLogout{} }
func (m *UserLogout) String() string { return proto.CompactTextString(m) }
func (*UserLogout) ProtoMessage()    {}

func (m *UserLogout) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *UserLogout) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type UserLogoutResponse struct {
	Status           *bool   `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	Extra            *string `protobuf:"bytes,2,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserLogoutResponse) Reset()         { *m = UserLogoutResponse{} }
func (m *UserLogoutResponse) String() string { return proto.CompactTextString(m) }
func (*UserLogoutResponse) ProtoMessage()    {}

func (m *UserLogoutResponse) GetStatus() bool {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return false
}

func (m *UserLogoutResponse) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type Message struct {
	MessageId        *string `protobuf:"bytes,1,req,name=message_id" json:"message_id,omitempty"`
	Sender           *string `protobuf:"bytes,2,req,name=sender" json:"sender,omitempty"`
	Receiver         *string `protobuf:"bytes,3,req,name=receiver" json:"receiver,omitempty"`
	MessageBody      *string `protobuf:"bytes,4,req,name=message_body" json:"message_body,omitempty"`
	Date             *int64  `protobuf:"varint,5,opt,name=date" json:"date,omitempty"`
	Extra            *string `protobuf:"bytes,6,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *Message) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *Message) GetReceiver() string {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return ""
}

func (m *Message) GetMessageBody() string {
	if m != nil && m.MessageBody != nil {
		return *m.MessageBody
	}
	return ""
}

func (m *Message) GetDate() int64 {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return 0
}

func (m *Message) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type MessageResponse struct {
	MessageId        *string `protobuf:"bytes,1,req,name=message_id" json:"message_id,omitempty"`
	Status           *bool   `protobuf:"varint,2,req,name=status" json:"status,omitempty"`
	Extra            *string `protobuf:"bytes,3,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}

func (m *MessageResponse) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *MessageResponse) GetStatus() bool {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return false
}

func (m *MessageResponse) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type ReceiveMessageAck struct {
	MessageId        *string `protobuf:"bytes,1,req,name=message_id" json:"message_id,omitempty"`
	Status           *int32  `protobuf:"varint,2,req,name=status" json:"status,omitempty"`
	Extra            *string `protobuf:"bytes,3,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReceiveMessageAck) Reset()         { *m = ReceiveMessageAck{} }
func (m *ReceiveMessageAck) String() string { return proto.CompactTextString(m) }
func (*ReceiveMessageAck) ProtoMessage()    {}

func (m *ReceiveMessageAck) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *ReceiveMessageAck) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *ReceiveMessageAck) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type NormalMessage struct {
	MessageId        *string `protobuf:"bytes,1,req,name=message_id" json:"message_id,omitempty"`
	Receiver         *string `protobuf:"bytes,2,req,name=receiver" json:"receiver,omitempty"`
	Content          []byte  `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	Date             *int64  `protobuf:"varint,4,req,name=date" json:"date,omitempty"`
	Expire           *int32  `protobuf:"varint,5,opt,name=expire" json:"expire,omitempty"`
	Extra            *string `protobuf:"bytes,6,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NormalMessage) Reset()         { *m = NormalMessage{} }
func (m *NormalMessage) String() string { return proto.CompactTextString(m) }
func (*NormalMessage) ProtoMessage()    {}

func (m *NormalMessage) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *NormalMessage) GetReceiver() string {
	if m != nil && m.Receiver != nil {
		return *m.Receiver
	}
	return ""
}

func (m *NormalMessage) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *NormalMessage) GetDate() int64 {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return 0
}

func (m *NormalMessage) GetExpire() int32 {
	if m != nil && m.Expire != nil {
		return *m.Expire
	}
	return 0
}

func (m *NormalMessage) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

type NormalMessageAck struct {
	MessageId        *string `protobuf:"bytes,1,req,name=message_id" json:"message_id,omitempty"`
	Status           *int32  `protobuf:"varint,2,req,name=status" json:"status,omitempty"`
	Extra            *string `protobuf:"bytes,3,opt,name=extra" json:"extra,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NormalMessageAck) Reset()         { *m = NormalMessageAck{} }
func (m *NormalMessageAck) String() string { return proto.CompactTextString(m) }
func (*NormalMessageAck) ProtoMessage()    {}

func (m *NormalMessageAck) GetMessageId() string {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return ""
}

func (m *NormalMessageAck) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *NormalMessageAck) GetExtra() string {
	if m != nil && m.Extra != nil {
		return *m.Extra
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.MessageCommand", MessageCommand_name, MessageCommand_value)
}
